export const words3 = [
    { word: "Fireman", emoji: ["🔥", "👨‍🚒", "🚒"] },
    { word: "Sailing", emoji: ["⛵", "🌊", "🌬️"] },
    { word: "Teacher", emoji: ["👨‍🏫", "📚", "✏️"] },
    { word: "Airport", emoji: ["✈️", "🏢", "🛄"] },
    { word: "Coconut", emoji: ["🥥", "🌴", "🏝️"] },
    { word: "Pumpkin", emoji: ["🎃", "🌱", "🍂"] },
    { word: "Swimmer", emoji: ["🏊‍♂️", "💦", "🏅"] },
    { word: "Holiday", emoji: ["🎄", "🏝️", "🎁"] },
    { word: "Factory", emoji: ["🏭", "⚙️", "🔧"] },
    { word: "amazing", emoji: ["✨", "🤩", "🔥"] },
    { word: "success", emoji: ["🏆", "🚀", "🎯", "💯"] },
    { word: "journey", emoji: ["🧭", "🌄", "👣", "🛤️", "✈️"] },
    { word: "pockets", emoji: ["👖", "🪙", "🕳️", "🤲"] },
    { word: "library", emoji: ["📚", "🦉", "🏛️"] },
    { word: "picture", emoji: ["📷", "🎨"] },
    { word: "forever", emoji: ["♾️", "💍", "⏳"] },
    { word: "wintery", emoji: ["❄️", "☕"] },
    { word: "freedom", emoji: ["🗽", "🏃", "🔓"] },
    { word: "society", emoji: ["👥", "🏙️", "🌐", "💬"] },
    { word: "imagine", emoji: ["🔮", "💭", "🌠"] },
    { word: "balance", emoji: ["🧘", "☯️"] },
    { word: "mystery", emoji: ["🔎", "❓", "👻"] },
    { word: "reality", emoji: ["📡", "👁️", "🌍", "🪞", "⚡"] },
    { word: "captain", emoji: ["👨‍✈️", "⚓"] },
    { word: "sunrise", emoji: ["🌅", "☀️", "🌤️", "🌄"] },
    { word: "diamond", emoji: ["💎"] },
    { word: "harvest", emoji: ["🌾", "🚜", "🍎", "🍂", "🛒"] },
    { word: "bicycle", emoji: ["🚲", "🛣️"] },
    { word: "monster", emoji: ["👹", "🌑", "💀", "👻"] },
    { word: "paradox", emoji: ["🤯", "🔄"] },
    { word: "silence", emoji: ["🤫", "🔇", "🌌"] },
    { word: "victory", emoji: ["🏆", "🎖️", "✌️"] },
    { word: "whisper", emoji: ["👂", "🏛️"] },
    { word: "miracle", emoji: ["🌟", "🙌", "✨"] },
    { word: "tornado", emoji: ["🌪️", "🏠", "💨"] },
    { word: "unicorn", emoji: ["🦄", "🌈"] },
    { word: "volcano", emoji: ["🌋", "🔥"] },
    { word: "quantum", emoji: ["🔬", "⚛️"] },
    { word: "Jubilee", emoji: ["🎉", "🥳", "🎶"] },
    { word: "Rescue", emoji: ["🛟", "🚒", "💪"] },
    { word: "Lenders", emoji: ["💵", "📈", "🏦"] },
    { word: "Chasing", emoji: ["🏃", "🐾", "⏳"] },
    { word: "Survive", emoji: ["🏕️", "🔥", "💪"] },
    { word: "Breathe", emoji: ["💨", "🌬️", "🌳"] },
    { word: "Frozen", emoji: ["❄️", "☃️", "🧊"] },
    { word: "Wander", emoji: ["🛤️", "👣", "🌍"] },
    { word: "Tropics", emoji: ["🌴", "🏖️", "🌞"] },
    { word: "Sunbeam", emoji: ["🌞", "🌟", "✨"] },
    { word: "Fighter", emoji: ["🥊", "💥", "👊"] },
    { word: "Catcher", emoji: ["🥎", "🧤", "⚾"] },
    { word: "Bravery", emoji: ["🦸‍♂️", "🔥", "💪"] },
    { word: "Wishing", emoji: ["🌠", "🎉", "🍀"] },
    { word: "Lending", emoji: ["💵", "💳", "🏦"] },
];
